/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
<<<<<<< HEAD
    "aws_cognito_identity_pool_id": "us-west-1:c0b7a1e4-e186-479c-aaca-60d160cb8250",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_CaU5vTwsi",
    "aws_user_pools_web_client_id": "l07csmn913fcahp2079vvmlja",
=======
    "aws_cognito_identity_pool_id": "us-west-1:4820a351-3879-423b-93e0-6a28b3e92d4e",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_gp60TrWKN",
    "aws_user_pools_web_client_id": "3ggq31t0j4pqnl692671qelmsh",
>>>>>>> main
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
<<<<<<< HEAD
        "EMAIL"
=======
        "EMAIL",
        "FAMILY_NAME",
        "GIVEN_NAME"
>>>>>>> main
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
